import type { Activity, Creator, Discount, Metric, Order, Product } from './types'

export const creator: Creator = {
  name: 'Mina Studio',
  handle: '@minastudio',
  followers: 128400,
  mrr: 84200,
  responseTime: '1h 18m',
  payoutStatus: 'Ready',
  taxStatus: 'Compliant',
}

export const products: Product[] = [
  {
    id: 'p-automation',
    title: 'Automation Field Manual',
    creator: 'Mina Studio',
    handle: '@minastudio',
    category: 'Operations',
    kind: 'Book',
    price: 39,
    compareAt: 79,
    sales: 18642,
    rating: 4.9,
    refundRate: 1.8,
    conversion: 7.4,
    status: 'Live',
    risk: 'Low',
    tags: ['No-code', 'AI ops', 'SOPs'],
    accent: '#ff6b35',
    description: 'A practical system for turning repeated service work into audited automation playbooks.',
    delivery: 'PDF, EPUB, Notion workspace, and 42 reusable prompts',
    license: 'Personal license with commercial client use allowed',
    updated: 'May 24, 2026',
  },
  {
    id: 'p-saas-kit',
    title: 'SaaS Launch Room',
    creator: 'Northstar Labs',
    handle: '@northstar',
    category: 'Startups',
    kind: 'Template',
    price: 149,
    sales: 7320,
    rating: 4.8,
    refundRate: 2.6,
    conversion: 5.9,
    status: 'Live',
    risk: 'Low',
    tags: ['Figma', 'React', 'Stripe'],
    accent: '#2ec4b6',
    description: 'Production screens, pricing models, onboarding flows, and investor-ready launch assets.',
    delivery: 'Figma files, React components, KPI workbook, and onboarding scripts',
    license: 'Team license for up to 12 seats',
    updated: 'May 18, 2026',
  },
  {
    id: 'p-membership',
    title: 'Creator CFO Membership',
    creator: 'Ledger House',
    handle: '@ledgerhouse',
    category: 'Finance',
    kind: 'Membership',
    price: 29,
    sales: 3940,
    rating: 4.7,
    refundRate: 3.2,
    conversion: 6.6,
    status: 'Live',
    risk: 'Medium',
    tags: ['Taxes', 'Payouts', 'Forecasts'],
    accent: '#3a86ff',
    description: 'Monthly operating reviews, tax-ready revenue models, and payout planning for solo founders.',
    delivery: 'Private community, live office hours, and downloadable finance systems',
    license: 'Monthly seat subscription',
    updated: 'May 26, 2026',
    subscription: '$29/mo',
  },
  {
    id: 'p-motion',
    title: 'Motion Brand Pack',
    creator: 'Frame Foundry',
    handle: '@framefoundry',
    category: 'Design',
    kind: 'Asset Pack',
    price: 89,
    compareAt: 129,
    sales: 11820,
    rating: 4.9,
    refundRate: 1.1,
    conversion: 8.1,
    status: 'Live',
    risk: 'Low',
    tags: ['After Effects', 'Social', 'Brand'],
    accent: '#ffbe0b',
    description: 'A full motion identity kit for product launches, social drops, and creator-led campaigns.',
    delivery: 'AE templates, ProRes exports, captions, and usage notes',
    license: 'Commercial license for unlimited owned channels',
    updated: 'May 21, 2026',
  },
  {
    id: 'p-course',
    title: 'High Trust Checkout Course',
    creator: 'Conversion Desk',
    handle: '@conversiondesk',
    category: 'Marketing',
    kind: 'Course',
    price: 249,
    sales: 5110,
    rating: 4.8,
    refundRate: 4.4,
    conversion: 4.8,
    status: 'Review',
    risk: 'Medium',
    tags: ['Checkout', 'Email', 'Upsells'],
    accent: '#8338ec',
    description: 'Checkout audits, launch sequences, and proof systems for digital products over $100.',
    delivery: '18 video lessons, templates, teardown library, and office hour replays',
    license: 'Individual lifetime access',
    updated: 'May 12, 2026',
  },
  {
    id: 'p-local',
    title: 'Local Services OS',
    creator: 'Service Stack',
    handle: '@servicestack',
    category: 'Business',
    kind: 'Template',
    price: 119,
    sales: 2860,
    rating: 4.6,
    refundRate: 5.1,
    conversion: 3.7,
    status: 'Paused',
    risk: 'High',
    tags: ['CRM', 'Scheduling', 'Invoices'],
    accent: '#06d6a0',
    description: 'A client pipeline, estimate workflow, and after-service follow-up system for local operators.',
    delivery: 'Airtable base, Zapier recipes, invoice templates, and SOPs',
    license: 'Single business license',
    updated: 'Apr 29, 2026',
  },
]

export const metrics: Metric[] = [
  { label: 'Net revenue', value: '$428.7k', delta: '+18.4%', tone: 'good' },
  { label: 'Conversion', value: '6.8%', delta: '+0.9%', tone: 'good' },
  { label: 'Refund rate', value: '2.7%', delta: '-0.4%', tone: 'good' },
  { label: 'Risk holds', value: '$8.2k', delta: '+1.1%', tone: 'warn' },
]

export const orders: Order[] = [
  {
    id: 'ORD-74021',
    customer: 'aisha@northwind.io',
    productId: 'p-saas-kit',
    amount: 149,
    status: 'Fulfilled',
    risk: 'Low',
    date: 'May 29, 2026',
    country: 'US',
    channel: 'Affiliate',
    licenseKey: 'BG-SAA-7J2K-L9P4',
  },
  {
    id: 'ORD-74020',
    customer: 'marco@studio.mx',
    productId: 'p-motion',
    amount: 89,
    status: 'Paid',
    risk: 'Low',
    date: 'May 29, 2026',
    country: 'MX',
    channel: 'Search',
    licenseKey: 'BG-MOT-9Q1X-R2V8',
  },
  {
    id: 'ORD-74019',
    customer: 'nora@ledger.dev',
    productId: 'p-membership',
    amount: 29,
    status: 'Paid',
    risk: 'Medium',
    date: 'May 28, 2026',
    country: 'GB',
    channel: 'Email',
    licenseKey: 'BG-CFO-5M8C-D4T1',
  },
  {
    id: 'ORD-74018',
    customer: 'devon@buildco.com',
    productId: 'p-course',
    amount: 249,
    status: 'Disputed',
    risk: 'High',
    date: 'May 28, 2026',
    country: 'CA',
    channel: 'Direct',
    licenseKey: 'BG-CHK-2N6H-X8A0',
  },
  {
    id: 'ORD-74017',
    customer: 'sara@pilot.app',
    productId: 'p-automation',
    amount: 39,
    status: 'Refunded',
    risk: 'Medium',
    date: 'May 27, 2026',
    country: 'US',
    channel: 'Social',
    licenseKey: 'BG-AUT-8C7V-Q2E9',
  },
]

export const activity: Activity[] = [
  { id: 'a-1', actor: 'Risk engine', event: 'Flagged unusual dispute velocity on High Trust Checkout Course', time: '9m ago', severity: 'Warning' },
  { id: 'a-2', actor: 'Payouts', event: 'Released $42,180 to Mina Studio bank account', time: '34m ago', severity: 'Info' },
  { id: 'a-3', actor: 'Content review', event: 'Queued Local Services OS for licensing review', time: '1h ago', severity: 'Critical' },
  { id: 'a-4', actor: 'Tax service', event: 'Validated W-9 and EU VAT evidence for 318 new buyers', time: '2h ago', severity: 'Info' },
]

export const discounts: Discount[] = [
  { code: 'BUILD20', value: 20, redemptions: 812, expires: 'Jun 14' },
  { code: 'LAUNCH50', value: 50, redemptions: 120, expires: 'May 31' },
  { code: 'TEAM15', value: 15, redemptions: 64, expires: 'Jul 02' },
]

export const revenueSeries = [42, 55, 48, 72, 66, 81, 94, 88, 103, 116, 128, 141]
